===== FTR-DOCUMENTATION-PUBLICATION — Publish the documentation artifacts

*Context*::
We want an adequate and attractive way to publish documentation artifacts for our project

*Goal*::
Prevent bloating the repo with checked in artifacts (problem with GitHubPages on the same repo)
Prevent an overly complex setup (cross repo token / deploy key management)  (problem with GitHubPages on a different repo)

*Soluton Idea*::
Antora

*Rationale*::
Project should become more accessible, documentation

*Acceptance*::
* the following solution possibilities are discussed with pros and cons and a decision is documented as an adr
** GitHub Pages on the same repo
** GitHub Pages on the same repo
** Antora
* artiacts comprise:
** user guide
** Various technical documents (e.g. dev guides, architecture documentation, ...)
** tutorials
* There are multiple sources that should be built in CI/CD
** asciidoc
** revaljs (not now but perhaps in the future)
* and a range of potenital output formats
** pdf downlaod
** html live view
* The presentation should be attractive to the user
* documentation is generated automatically

